In [ ]:
# TASK 1

In [5]:
import numpy as np
np.random.seed(125)
np.float64(np.random.randint(10, 100, size = (4, 1, 3, 4))*10)

array([[[[710., 390., 970., 770.],
         [870., 960., 530., 690.],
         [740., 470., 960., 370.]]],


       [[[400., 630., 680., 100.],
         [940., 600., 990., 420.],
         [970., 400., 760., 190.]]],


       [[[130., 630., 860., 570.],
         [540., 170., 380., 510.],
         [190., 910., 140., 780.]]],


       [[[910., 480., 450., 270.],
         [460., 850., 510., 570.],
         [960., 880., 330., 960.]]]])

In [ ]:
# TASK 2

In [ ]:
# DO LATER

In [ ]:
# TASK 3

In [11]:
class Compare1: 
    @classmethod
    def Loop(cls, num= 10000):
        val = list(range(1, num, 1))
        
        numbers = []        
        for i in val:
            res = i*25
            numbers.append(res) 
        return numbers

c2 = Compare1()
c2.Loop(10)

[25, 50, 75, 100, 125, 150, 175, 200, 225]

In [12]:
class Compare2:
    import numpy as np
    
    @classmethod
    def Loop(cls, num = 10000):
        val = list(range(1, num, 1)) 
        numbers = cls.np.array(val)*25 
        return numbers.tolist()

c2 = Compare2()
c2.Loop(10)

[25, 50, 75, 100, 125, 150, 175, 200, 225]

In [ ]:
# TASK 4

In [15]:
class Gen_numpy:
    import numpy as np
    
    @classmethod   
    def Array_gen(cls, *args): 
        cls.np.random.seed(12)
        case = []
        for i in args:
            res = i 
            case.append(res) 
            tup = tuple(case)
        arr1 = cls.np.random.randint(1, 100, size = tup) 
        
        gen = (i for i in arr1)
        return gen

gp = Gen_numpy()
g = gp.Array_gen(4, 3, 2, 3)
next(g)

array([[[76, 28,  7],
        [ 3,  4, 68]],

       [[77, 49, 23],
        [50, 53,  6]],

       [[14, 90, 35],
        [76, 75,  1]]])

In [ ]:
# TASK 5

In [32]:
np.random.seed(1200)

arr5 = np.random.randint(1, 100, size = (3, 5, 2))
arr5[0][[0, 4], [0, 1]] * arr5[1][[3], [0]] + arr5[2][3][0]

array([4611, 3477])