In [1]:
import numpy as np

In [12]:
np.random.seed(123)
rad = np.random.rand(20)
rad

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897,
       0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752,
       0.34317802, 0.72904971, 0.43857224, 0.0596779 , 0.39804426,
       0.73799541, 0.18249173, 0.17545176, 0.53155137, 0.53182759])

In [13]:
import sys
sys.getsizeof(rad)
from sys import getsizeof as size
size(rad)

256

In [14]:
np.savetxt("numpy_file.txt", rad, newline = "\n", header = "NUMPY", footer = "END!")

In [15]:
np.loadtxt("numpy_file.txt")

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897,
       0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752,
       0.34317802, 0.72904971, 0.43857224, 0.0596779 , 0.39804426,
       0.73799541, 0.18249173, 0.17545176, 0.53155137, 0.53182759])

In [20]:
np.random.seed(121)
rad2 = np.random.randn(2, 5, 2)
rad2
np.save("small_array", rad2)
rad2

array([[[-0.21203317, -0.28492917],
        [-0.57389821, -0.44031017],
        [-0.33011056,  1.18369457],
        [ 1.61537293,  0.36706247],
        [-0.01411931,  0.6296418 ]],

       [[ 1.70964074, -1.32698736],
        [ 0.40187312, -0.19142667],
        [ 1.40382596, -1.96876855],
        [-0.79041516, -0.73272161],
        [ 0.08774382, -0.500286  ]]])

In [21]:
np.load("small_array.npy")

array([[[-0.21203317, -0.28492917],
        [-0.57389821, -0.44031017],
        [-0.33011056,  1.18369457],
        [ 1.61537293,  0.36706247],
        [-0.01411931,  0.6296418 ]],

       [[ 1.70964074, -1.32698736],
        [ 0.40187312, -0.19142667],
        [ 1.40382596, -1.96876855],
        [-0.79041516, -0.73272161],
        [ 0.08774382, -0.500286  ]]])

In [27]:
np.random.seed(121)
val1 = np.random.randn(4, 1000, 100)
val1
size(val1)
val2 = np.random.randn(2, 8)
val2
size(val2)
val3 = np.random.randn(2, 4, 1)
size(val3)

192

In [29]:
size(val1)
np.savez_compressed("comp_data", val1)

In [30]:
val_comp = np.load("comp_data.npz")

In [31]:
size(val_comp)

64

In [32]:
val_comp.keys()

KeysView(<numpy.lib.npyio.NpzFile object at 0x11f256d10>)

In [35]:
size(val_comp["arr_0"])

3200128

In [36]:
np.savez_compressed("comp_data2", a = val1, b = val2, c = val3)

In [38]:
val_comp2 = np.load("comp_data2.npz")
size(val_comp2)

64

In [39]:
val_comp.keys()

KeysView(<numpy.lib.npyio.NpzFile object at 0x11f256d10>)

In [40]:
val_comp2["a"]

array([[[-0.21203317, -0.28492917, -0.57389821, ...,  1.32124954,
         -1.13258159,  0.32202602],
        [-0.88244732, -0.2484412 , -0.3597747 , ..., -1.52130688,
          1.49863356,  2.32682172],
        [ 0.02012755, -0.37775322, -0.28720805, ...,  1.52344443,
          1.81660472, -0.25848147],
        ...,
        [ 1.25574609, -1.87065337,  0.85153806, ...,  0.23293323,
         -0.49225843, -0.89896021],
        [-1.20766519, -1.92250559,  1.18954724, ..., -0.29215511,
         -1.61486967, -0.40924104],
        [ 0.8291337 ,  0.98949885, -1.81646919, ...,  0.12992383,
          0.13717114, -1.53501323]],

       [[ 0.33502977,  0.59007697, -0.80485114, ...,  0.76841823,
          1.06949311,  1.56069087],
        [ 0.50496447,  0.55404733,  1.19278272, ..., -1.28251743,
         -2.185976  , -0.31329218],
        [ 0.24728346,  0.67159096, -0.4720875 , ..., -1.17283913,
         -2.33571395, -1.39792695],
        ...,
        [ 0.08302539,  0.24618209, -0.15337696, ..., -