In [1]:
import numpy as np

In [12]:
arr = np.arange(1, 21, dtype = "float64").reshape(2, 10).T
arr

array([[ 1., 11.],
       [ 2., 12.],
       [ 3., 13.],
       [ 4., 14.],
       [ 5., 15.],
       [ 6., 16.],
       [ 7., 17.],
       [ 8., 18.],
       [ 9., 19.],
       [10., 20.]])

In [22]:
# NaN = Not a Number
arr[5] = np.nan, np.nan
arr[2] = 3.0, np.nan
arr[7:9, 0:1] = np.nan
arr

array([[ 1., 11.],
       [ 2., 12.],
       [ 3., nan],
       [ 4., 14.],
       [ 5., 15.],
       [nan, nan],
       [ 7., 17.],
       [nan, 18.],
       [nan, 19.],
       [10., 20.]])

In [28]:
np.nan_to_num(arr) # CONVERTS NaN VALUES TO 0
np.nan_to_num(arr).min()

0.0

In [29]:
np.nanmin(arr)

1.0

In [34]:
arr2 = np.array([10, 20, np.nan, 30, np.nan])
arr2[~np.isnan(arr2)]

array([10., 20., 30.])

In [64]:
lin = np.linspace(1, 10, num = 20)

In [46]:
np.zeros(4)
np.zeros((4, 2))
np.ones((4, 4)) / 2

array([[0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5]])

In [60]:
np.identity(4)
np.eye(4, k = 0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
np.diag([10, 20, 30, 40])

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

In [65]:
np.ones_like(lin)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [72]:
a = np.array([10, 5])
b = np.array([20, 2, 30, 4]).reshape(2, 2)
c = np.array([10, 5, 100, 8]).reshape(2, 2)
np.dot(b, c)

array([[400, 116],
       [700, 182]])

In [74]:
np.prod(a)
np.prod(b)

4800

In [76]:
np.linalg.det(b) # (20*4) - (30*2) ~= 20

19.999999999999996

In [77]:
b 

array([[20,  2],
       [30,  4]])