In [1]:
import numpy as np

In [3]:
len(dir(np))

624

In [4]:
num = list(range(10, 60, 10))
num

[10, 20, 30, 40, 50]

In [6]:
vec = np.array(num)
vec.dtype

dtype('int64')

In [7]:
type(vec) # ndarray = n dimensional array

numpy.ndarray

In [15]:
vec
np.array([10, 12.4])
np.array([10, 12.123]).dtype

dtype('float64')

In [17]:
vec.astype("<U32")

array(['10', '20', '30', '40', '50'], dtype='<U32')

In [19]:
num * 3

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

In [25]:
vec * 3
vec + 100
vec - 23
vec / 3
vec // 3
vec ** 2

array([ 100,  400,  900, 1600, 2500])

In [29]:
num + num
print(num)
print(vec)
num + vec
num * vec

[10, 20, 30, 40, 50]
[10 20 30 40 50]


array([ 100,  400,  900, 1600, 2500])

In [32]:
vec2  = vec**2
vec2.tolist()

[100, 400, 900, 1600, 2500]

In [36]:
%%timeit -r 1 -n 1
case = []
for i in range(len(val)):
    res = val[i]**2
    case.append(res)    
case

337 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [37]:
%%timeit -r 1 -n 1
[val[i]**2 for i in range(len(val))]

311 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [35]:
val = list(range(1, 1000001, 1))
len(val)

1000000

In [38]:
%%timeit -r 1 -n 1 # About 3 times faster than a list comprehension
vec3 = np.array(val)**2
vec3.tolist()

109 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [39]:
ran = list(range(1, 21, 2))
ran

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [49]:
zoom = np.arange(1, 21, 2)
zoom.reshape(10, 1).shape
zoom.shape

(10,)

In [62]:
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
mat.ndim
mat[2] = 10, 20, 30
mat[2]
mat[0:2]
mat[:, 0:2]
mat[1:, 1:3]
mat[1:2, 1:2]

array([[5]])

In [57]:
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [65]:
mat[1:2, 1:2]

array([[5]])