In [1]:
import numpy as np

In [5]:
arr1 = np.arange(1, 9).reshape(2, 4)
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2 = np.arange(1, 17).reshape(4, 4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [13]:
arr1.T.shape
arr2.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [16]:
arr2[1] = 2, 90, 3, 20
arr2

array([[ 1,  2,  3,  4],
       [ 2, 90,  3, 20],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
arr2.sum()
arr2.sum(0) # Columns
arr2.sum(1) # Rows

array([ 10, 115,  42,  58])

In [23]:
arr2.max()
arr2.max(0)
arr2.max(1)

array([ 4, 90, 12, 16])

In [33]:
arr2.var()
arr2.std()
arr2.min()
arr2.mean()
arr2.argmax()
arr2.argmin()

0

In [34]:
arr2.flatten()[0]

1

In [30]:
arr2

array([[ 1,  2,  3,  4],
       [ 2, 90,  3, 20],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [37]:
arr2.cumsum()
arr2.cumsum(0)
arr2.cumsum(1)

array([[  1,   3,   6,  10],
       [  2,  92,  95, 115],
       [  9,  19,  30,  42],
       [ 13,  27,  42,  58]])

In [39]:
arr2 > 7

array([[False, False, False, False],
       [False,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [45]:
arr2[(arr2 > 7) | (arr2 < 14)]

array([ 1,  2,  3,  4,  2, 90,  3, 20,  9, 10, 11, 12, 13, 14, 15, 16])

In [47]:
letters = ["a", "b", "c"]
val = [10, 20, 30]
cond = [True, False, True]
for i in np.where(cond, letters, val):
    print(i)

a
20
c


In [51]:
arr2[1] > 10
word = ["python", "javascript", "C#", "Julia"]
np.where(arr2[1] > 10, arr2[1], word)

array(['python', '90', 'C#', '20'], dtype='<U21')

In [53]:
np.where((arr2 > 10), 1, -1)

array([[-1, -1, -1, -1],
       [-1,  1, -1,  1],
       [-1, -1,  1,  1],
       [ 1,  1,  1,  1]])

In [52]:
arr2

array([[ 1,  2,  3,  4],
       [ 2, 90,  3, 20],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [59]:
num = [100, 200, 300, 400]
np.insert(arr2, 2, num)
np.insert(arr2, 4, num, axis = 0)
np.insert(arr2, 4, num, axis = 1)

array([[  1,   2,   3,   4, 100],
       [  2,  90,   3,  20, 200],
       [  9,  10,  11,  12, 300],
       [ 13,  14,  15,  16, 400]])