In [1]:
import numpy as np, sys, math, random as rd

In [9]:
np.random.seed(123)
np.random.randint(1, 50, size = (2, 10))

array([[46,  3, 29, 35, 39, 18, 20, 43, 23, 34],
       [33, 48, 10, 33, 47, 33, 48, 26, 20, 15]])

In [30]:
np.random.seed(1200)
np.int32(np.random.rand(3, 5,2)*100) # Last two values are row and column

array([[[56, 96],
        [67, 85],
        [ 7, 35],
        [14, 26],
        [48, 98]],

       [[49, 18],
        [34, 55],
        [83, 54],
        [77, 39],
        [77, 69]],

       [[36,  7],
        [47, 86],
        [59, 16],
        [99, 66],
        [98, 45]]], dtype=int32)

In [33]:
np.random.randn(3, 5,2)

array([[[ 0.20247495, -0.48016887],
        [-0.48525339, -0.03655555],
        [ 0.02414925, -0.70036475],
        [ 0.96921842, -0.37051188],
        [-0.41626912, -0.13697739]],

       [[ 0.83820223, -0.39980212],
        [ 0.99063953, -1.05165767],
        [-0.08290372,  1.52649216],
        [ 1.26800199,  0.59340255],
        [-1.56036219,  0.71428959]],

       [[ 1.25832991, -0.28352251],
        [-0.79123404,  0.12290222],
        [ 0.4501173 ,  0.03049324],
        [ 0.17451478,  0.4379427 ],
        [ 1.60259333,  0.86578007]]])