In [1]:
import pandas as pd, numpy as np

In [3]:
rad = pd.DataFrame([[10, 20, 30], [1, 2, 3]], columns = ["A", "B", "C"], index = ["X", "Y"])
rad

,A,B,C
X,10,20,30
Y,1,2,3


In [6]:
np.random.seed(12)
data = [np.random.randint(1, 50, 10), 
        np.random.randint(1, 50, 10), 
        np.random.randint(1, 50, 10), 
        np.random.randint(1, 50, 10),]
data

[array([12, 28,  7,  3,  4,  4, 13, 49, 23,  6]),
 array([14, 26, 35, 12, 11,  1, 41, 13, 14, 19]),
 array([26, 36, 37, 36, 34, 31, 33, 19, 23, 17]),
 array([21,  7, 46, 10, 46, 31, 49, 33, 47, 28])]

In [9]:
let = list("abcdefghij")

df = pd.DataFrame({"W": data[0], "X": data[1], "Y": data[2], "Z": data[3]})
df

,W,X,Y,Z
0,12,14,26,21
1,28,26,36,7
2,7,35,37,46
3,3,12,36,10
4,4,11,34,46
5,4,1,31,31
6,13,41,33,49
7,49,13,19,33
8,23,14,23,47
9,6,19,17,28


In [10]:
type(df)

pandas.core.frame.DataFrame

In [11]:
type(df["W"])

pandas.core.series.Series

In [18]:
df["W"]
df[0:3] # Cannot do indexing

,W,X,Y,Z
0,12,14,26,21
1,28,26,36,7
2,7,35,37,46


In [22]:
df[["W", "X"]][:4][::-1]

,W,X
3,3,12
2,7,35
1,28,26
0,12,14


In [24]:
df.describe()
df.info() # Does to apply to series

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   W       10 non-null     int64
 1   X       10 non-null     int64
 2   Y       10 non-null     int64
 3   Z       10 non-null     int64
dtypes: int64(4)
memory usage: 448.0 bytes


In [31]:
df.head(2)
df.tail(1)

,W,X,Y,Z
9,6,19,17,28


In [36]:
df.shape
df["W"].shape
df[["W", "X"]].shape

(10, 2)

In [41]:
df.index
df.keys()
list(df)

['W', 'X', 'Y', 'Z']

In [47]:
df ** 2

,W,X,Y,Z
0,144,196,676,441
1,784,676,1296,49
2,49,1225,1369,2116
3,9,144,1296,100
4,16,121,1156,2116
5,16,1,961,961
6,169,1681,1089,2401
7,2401,169,361,1089
8,529,196,529,2209
9,36,361,289,784


In [54]:
df.sum()
df.mean()
df.max()
df.min()
df.var()
df.std()

W    14.654920
X    12.066483
Y     7.420692
Z    15.468965
dtype: float64

In [55]:
df[["X", "Y"]].sum()

X    186
Y    292
dtype: int64

In [56]:
df.values

array([[12, 14, 26, 21],
       [28, 26, 36,  7],
       [ 7, 35, 37, 46],
       [ 3, 12, 36, 10],
       [ 4, 11, 34, 46],
       [ 4,  1, 31, 31],
       [13, 41, 33, 49],
       [49, 13, 19, 33],
       [23, 14, 23, 47],
       [ 6, 19, 17, 28]])

In [62]:
# df.as_matrix

In [63]:
df2 = df.copy()

In [68]:
df2["A2"] = 1
df2["B2"] = df2.W * 3 
df2["C2"] = np.random.randint(1, 50, 10)
df2

,W,X,Y,Z,A2,B2,C2
0,12,14,26,21,1,36,26
1,28,26,36,7,1,84,25
2,7,35,37,46,1,21,16
3,3,12,36,10,1,9,26
4,4,11,34,46,1,12,34
5,4,1,31,31,1,12,5
6,13,41,33,49,1,39,33
7,49,13,19,33,1,147,5
8,23,14,23,47,1,69,2
9,6,19,17,28,1,18,44


In [69]:
letters = ["A2", "B2"]
for i in df2.columns:
    if i in letters:
        del df2[i]

In [71]:
del df2["C2"]

In [72]:
df2

,W,X,Y,Z
0,12,14,26,21
1,28,26,36,7
2,7,35,37,46
3,3,12,36,10
4,4,11,34,46
5,4,1,31,31
6,13,41,33,49
7,49,13,19,33
8,23,14,23,47
9,6,19,17,28


In [73]:
np.random.seed(12)
ds = pd.Series(np.random.randint(1, 50, 10), name = "Series")
ds

0    12
1    28
2     7
3     3
4     4
5     4
6    13
7    49
8    23
9     6
Name: Series, dtype: int64

In [75]:
pd.concat([df2, ds], axis = 1)

,W,X,Y,Z,Series
0,12,14,26,21,12
1,28,26,36,7,28
2,7,35,37,46,7
3,3,12,36,10,3
4,4,11,34,46,4
5,4,1,31,31,4
6,13,41,33,49,13
7,49,13,19,33,49
8,23,14,23,47,23
9,6,19,17,28,6
